apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - todo-secret-sealed.json
images:
  - name: melmanmankiewicz/todo_frontend
    newName: melmanmankiewicz/todo_frontend
    newTag: red1.0
#patchesStrategicMerge:
#  - todo_frontend.yaml
