apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-secret-sealed.json
  - ../../base
images:
  - name: melmanmankiewicz/todo_frontend
    newName: melmanmankiewicz/todo_frontend
    newTag: with_image
