apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-secret-sealed.json
- ../../base
images:
- name: todo_frontend
  newName: melmanmankiewicz/todo_frontend
  newTag: 2022-05-02_09-04-29
